/*
 * File Overview
 * Purpose: DOM cache and selectors for key UI elements.
 * Controls: References to grid, modals, buttons, HUD, and other UI nodes.
 * How: Queries the document once and exports a stable els map for reuse.
 * Key interactions: Used by UI modules to avoid repeated DOM queries.
 */
// DOM cache for frequently used nodes.
const $ = (s) => document.querySelector(s);

export const els = {
  logo: $("#logo"),
  stage: $("#stage"),
  gridScroll: $("#gridScroll"),
  grid: $("#grid"),
  reveal: $("#reveal"),
  resultsModal: $("#results"),
  resultsClose: $(".resultsClose"),
  resultsShare: $(".resultsShare"),
  slider: $(".game-slider"),
  puzzleActions: $(".puzzle-actions"),
  splash: $("#splashModal"),
  splashPrimary: $("#splashPrimary"),
  splashPuzzleBtn: $("#splashPuzzleBtns"),
  splashArchiveBtn: $("#splashArchiveBtn"),
  splashTutorialBtn: $("#splashTutorialBtn"),
  splashDate: $("#splashDate"),
  splashTitle: $("#splashTitle"),
  splashSubtitle: $("#splashSubtitle"),
  splashAvgTime: $("#splashAvgTime"),
  splashGamesPlayed: $("#splashGamesPlayed"),
  splashVersion: $("#splashVersion"),
  settingsBtn: $("#settingsBtn"),
  settingsPanel: $("#settingsPanel"),
  settingsCloseBtn: $("#settingsCloseBtn"),
  archiveModal: $("#archiveModal"),
  archiveBackBtn: $("#archiveBackBtn"),
  archivePrevMonth: $("#archivePrevMonth"),
  archiveNextMonth: $("#archiveNextMonth"),
  archiveMonthSelect: $("#archiveMonthSelect"),
  archiveYearSelect: $("#archiveYearSelect"),
  archiveCalendar: $("#archiveCalendar"),
  archiveTodayBtn: $("#archiveTodayBtn"),
  archiveActionBtn: $("#archiveActionBtn"),
  archiveActionLabel: $("#archiveActionLabel"),
  archiveActionMeta: $("#archiveActionMeta"),
  giveUpModal: $("#giveUpModal"),
  giveUpSubtitle: $(".giveUpSubtitle"),
  giveUpUnsolvedLine: $(".giveUpUnsolvedLine"),
  giveUpWordsCount: $(".giveUpWordsCount"),
  giveUpWordLabel: $(".giveUpWordLabel"),
  giveUpSeconds: $(".giveUpSeconds"),
  giveUpConfirm: $("#giveUpConfirm"),
  giveUpCancel: $("#giveUpCancel"),
  navWordPrev: $("#navWordPrev"),
  navCellPrev: $("#navCellPrev"),
  navCellNext: $("#navCellNext"),
  navWordNext: $("#navWordNext"),
  ftueModal: $("#ftueModal"),
  ftuePrev: $(".ftue-prev"),
  ftueNext: $(".ftue-next"),
  ftueSkip: $(".ftue-skip"),
  ftueStepLabel: $(".ftue-step-label"),
  ftueTitle: $("#ftueTitle"),
  ftueDesc: $(".ftue-desc"),
  ftueTip: $(".ftue-tip"),
  ftueDots: document.querySelectorAll(".ftue-dot"),
  ftueToast: $(".ftue-toast"),
  ftueGrid: $("#ftueGrid"),
  ftueGridScroll: $("#ftueGridScroll"),
  ftuePlayPause: $(".ftue-playpause"),
  ftuePlayPauseIcon: $(".ftue-playpause-icon"),
  pClear: $("#pClear"),
  status: $("#status"),
  helper: $(".helper"),
  keyboard: $(".keyboard"),
  archiveDate: $("#archiveDate"),
  toastSuccess: $("#toastSuccess"),
  toastWarning: $("#toastWarning"),
  toastError: $("#toastError"),
  toastErrorPuzzle: $("#toastError-puzzle"),
  toastWordSolved: $("#toastWordSolved"),
  toastHint: $("#toastHint"),
  hintPenalty: $("#hintPenalty"),
  splashShareToast: $("#splashShareToast"),
  shareBtn: $("#shareBtn"),
  viewResultsBtn: $("#viewResults"),
  autoCheckToggle: $("#autoCheckToggle"),
  showOnscreenKeyboard: $("#showOnscreenKeyboard"),
  totalHintPenalty: $("#totalHintPenalty"),
  totalWordPenalty: $("#totalWordPenalty"),
};
