/*
 * File Overview
 * Purpose: DOM cache and selectors for key UI elements.
 * Controls: References to grid, modals, buttons, HUD, and other UI nodes.
 * How: Queries the document once and exports a stable els map for reuse.
 * Key interactions: Used by UI modules to avoid repeated DOM queries.
 */
// DOM cache for frequently used nodes.
const $ = (s) => document.querySelector(s);

export const els = {
  logo: $("#logo"),
  stage: $("#stage"),
  gridScroll: $("#gridScroll"),
  grid: $("#grid"),
  reset: $("#reset"),
  reveal: $("#reveal"),
  resultsModal: document.getElementById("results"),
  resultsClose: document.querySelector(".resultsClose"),
  resultsShare: document.querySelector(".resultsShare"),
  slider: $(".game-slider"),
  nextPuzzleBtn: $("#nextPuzzleBtn"),
  puzzleActions: document.querySelector(".puzzle-actions"),
  splash: $("#splashModal"),
  splashPrimary: $("#splashPrimary"),
  splashPuzzleBtn: document.querySelector("#splashPuzzleBtns, #splashPuzzleBtn"),
  splashArchiveBtn: $("#splashArchiveBtn"),
  splashTutorialBtn: $("#splashTutorialBtn"),
  splashDate: $("#splashDate"),
  splashTitle: $("#splashTitle"),
  splashSubtitle: $("#splashSubtitle"),
  splashAvgTime: $("#splashAvgTime"),
  splashGamesPlayed: $("#splashGamesPlayed"),
  splashVersion: $("#splashVersion"),
  settingsBtn: $("#settingsBtn"),
  settingsPanel: $("#settingsPanel"),
  settingsCloseBtn: $("#settingsCloseBtn"),
  archiveModal: $("#archiveModal"),
  archiveDialog: document.querySelector(".archive__dialog"),
  archiveBackBtn: $("#archiveBackBtn"),
  archivePrevMonth: $("#archivePrevMonth"),
  archiveNextMonth: $("#archiveNextMonth"),
  archiveMonthSelect: $("#archiveMonthSelect"),
  archiveYearSelect: $("#archiveYearSelect"),
  archiveCalendar: $("#archiveCalendar"),
  archiveTodayBtn: $("#archiveTodayBtn"),
  archiveActionBtn: $("#archiveActionBtn"),
  archiveActionLabel: $("#archiveActionLabel"),
  archiveActionMeta: $("#archiveActionMeta"),
  giveUpModal: $("#giveUpModal"),
  giveUpSubtitle: document.querySelector(".giveUpSubtitle"),
  giveUpUnsolvedLine: document.querySelector(".giveUpUnsolvedLine"),
  giveUpWordsCount: document.querySelector(".giveUpWordsCount"),
  giveUpWordLabel: document.querySelector(".giveUpWordLabel"),
  giveUpSeconds: document.querySelector(".giveUpSeconds"),
  giveUpConfirm: $("#giveUpConfirm"),
  giveUpCancel: $("#giveUpCancel"),
  navWordPrev: $("#navWordPrev"),
  navCellPrev: $("#navCellPrev"),
  navCellNext: $("#navCellNext"),
  navWordNext: $("#navWordNext"),
  ftueModal: $("#ftueModal"),
  ftuePrev: document.querySelector(".ftue-prev"),
  ftueNext: document.querySelector(".ftue-next"),
  ftueSkip: document.querySelector(".ftue-skip"),
  ftueStepLabel: document.querySelector(".ftue-step-label"),
  ftueTitle: document.querySelector("#ftueTitle"),
  ftueDesc: document.querySelector(".ftue-desc"),
  ftueTip: document.querySelector(".ftue-tip"),
  ftueDots: document.querySelectorAll(".ftue-dot"),
  ftueToast: document.querySelector(".ftue-toast"),
  ftueGrid: $("#ftueGrid"),
  ftueGridScroll: $("#ftueGridScroll"),
  ftueDialog: document.querySelector(".ftue-modal__dialog"),
  ftuePlayPause: document.querySelector(".ftue-playpause"),
  ftuePlayPauseIcon: document.querySelector(".ftue-playpause-icon"),
  pClear: $("#pClear"),
  status: $("#status"),
  helper: $(".helper"),
  keyboard: $(".keyboard"),
  archiveDate: $("#archiveDate"),
  toastSuccess: $("#toastSuccess"),
  toastWarning: $("#toastWarning"),
  toastError: $("#toastError"),
  toastErrorPuzzle: $("#toastError-puzzle"),
  toastWordSolved: $("#toastWordSolved"),
  toastHint: $("#toastHint"),
  hintPenalty: $("#hintPenalty"),
  shareInline: $("#shareInline"),
  splashShareToast: $("#splashShareToast"),
  shareBtn: $("#shareBtn"),
  autoCheckToggle: $("#autoCheckToggle"),
  showOnscreenKeyboard: $("#showOnscreenKeyboard"),
  totalHintPenalty: $("#totalHintPenalty"),
  totalWordPenalty: $("#totalWordPenalty"),
};
