# .github/workflows/build-tokens.yml
name: Build Tokens

on:
  push:
    branches: [ main ]
    paths:
      - "tokens/raw/**"
      - "sd-configs/**"
      - "tools/**"
      - "package.json"
  pull_request:
    paths:
      - "tokens/raw/**"
      - "sd-configs/**"
      - "tools/**"
      - "package.json"
  workflow_dispatch:
    inputs:
      config:
        description: "Build only this config from sd-configs/ (e.g. css-primary.mjs)"
        required: false
        default: ""

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Build tokens
        run: npm run build
        env:
          SD_CONFIG: ${{ github.event.inputs.config }}

      - name: Commit generated files back
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "chore(tokens): rebuild outputs [skip ci]"
          file_pattern: tokens/resolved/**
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
