name: Token Converter

on:
  workflow_dispatch: {}
  push:
    paths:
      - 'tokens/raw/**/*.json'
      - 'tokens/style-dictionary/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/token-converter.yml'

permissions:
  contents: write

concurrency:
  group: token-converter
  cancel-in-progress: true

jobs:
  build:
    # Belt & suspenders: don't re-run on our own bot commits even if triggers expand later
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Intentionally not enabling automatic npm cache here to avoid lockfile warnings

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Ensure output dir exists
        run: mkdir -p tokens/resolved

      - name: Build tokens → CSS
        env:
          CI: true
        run: npm run build:tokens

      - name: Verify at least one non-empty CSS output
        run: |
          # Fail if no non-empty .css files exist in tokens/resolved/
          COUNT=$(find tokens/resolved -maxdepth 1 -type f -name '*.css' -size +0c | wc -l | tr -d ' ')
          if [ "$COUNT" -eq 0 ]; then
            echo "No non-empty CSS outputs found in tokens/resolved/"
            ls -la tokens/resolved || true
            exit 1
          fi

      - name: Show outputs (for debugging)
        run: |
          echo "Built files:"
          ls -la tokens/resolved || true

      - name: Commit & push if changed (any files under tokens/resolved/)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Stage all adds/updates/deletions in tokens/resolved
          git add -A tokens/resolved

          # Commit only if there are staged changes
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            FILES="$(git diff --cached --name-only | tr '\n' ' ')"
            git commit -m "chore(tokens): rebuild ${FILES} from ${GITHUB_SHA::7} [skip ci]"
            git push
          fi
