name: Build tokens

on:
  workflow_dispatch:
  push:
    paths:
      - "tokens/raw/**/*.json"
      - "tools/style-dictionary/**"
      - ".github/workflows/tokens.yml"

permissions:
  contents: write   
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i --no-audit --no-fund

      - name: Build tokens
        run: node tools/style-dictionary/build.mjs

      - name: Cleanup stray root resolved folder (if any)
        run: rm -rf resolved || true

      - name: Show diff (debug)
        run: |
          git status
          git diff -- tokens/resolved/tokens-test.css || true

      - name: Commit generated file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add tokens/resolved/tokens-test.css
          git commit -m "chore(tokens): update tokens-test.css [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${GITHUB_REF_NAME}
