name: Build tokens

on:
  push:
    paths:
      - "raw/**"
      - "tokens/**"
      - "sd-configs/**"
      - "tools/style-dictionary/**"
      - "package.json"
      - "package-lock.json"
  pull_request:
    paths:
      - "raw/**"
      - "tokens/**"
      - "sd-configs/**"
      - "tools/style-dictionary/**"
      - "package.json"
      - "package-lock.json"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required to push

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            echo "Using npm ci"
            npm ci
          else
            echo "No lockfile found; using npm install"
            npm install --no-audit --no-fund
          fi

      - name: Build tokens
        run: node tools/style-dictionary/build.mjs
        env:
          SD_CONFIG: sd-configs/css.mjs

      - name: Show diff (debug)
        run: |
          echo "Changed files:"
          git status --porcelain
          echo
          git --no-pager diff --stat || true

      - name: Commit generated files back
        if: github.event_name != 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add resolved/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(tokens): rebuild resolved tokens [skip ci]"
            git push
          fi
